FROM python:3.11-slim

WORKDIR /app

# Install dependencies
COPY backend/requirements.txt /app/backend/requirements.txt

RUN pip install --no-cache-dir -r /app/backend/requirements.txt

# Copy source
COPY backend /app/backend
COPY cache /app/cache
# COPY .env /app/.env
ENV PYTHONPATH=/app
ENV PYTHONUNBUFFERED=1

# Command
CMD ["python", "backend/worker.py"]
